# Generated by Django 4.1.4 on 2023-03-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_savedshoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedshoes',
            name='shoes',
        ),
        migrations.AddField(
            model_name='savedshoes',
            name='shoes',
            field=models.ManyToManyField(to='shoes.shoes'),
        ),
    ]
