# Generated by Django 4.1.4 on 2023-03-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_brand_categories_alter_shoes_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='images/logo'),
        ),
    ]
