# Generated by Django 4.1.4 on 2023-03-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_alter_brand_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='shoes',
            options={'verbose_name': 'Shoe', 'verbose_name_plural': 'Shoes'},
        ),
    ]
