# Generated by Django 4.1.7 on 2023-04-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0008_shoes_created_at_shoes_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='category',
        ),
        migrations.AddField(
            model_name='shoes',
            name='category',
            field=models.ManyToManyField(to='shoes.categories'),
        ),
    ]
